
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.c47833eb7eca483e
            client-secret: 1aa0bbf74b4d3e8c86b028279f032078aee71a7c

  data:
    cassandra:
      keyspace-name: main
      username: gZXNnccnbjZYvkNMebRFHbvq
      password: uSp_LgdP3guIOMM.iAI5WgYfizJ1W+QRlbsfBMzaac1zkCafSei8ilGDh3Qo6q.5HZh66GJmGKRGh_Jed5EAZzJf,+O+U3GacPaf1Cs-3mS6Dljqvjdy.lecyXWG9kg+
      schema-action: create_if_not_exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
  main:
    allow-circular-references: true
  application:
    name: book-reviewer-app

datastax.astra:
  secure-connect-bundle: secure-connect-bookstracker.zip


astra.db:
  id: 1c0b3c3e-033b-487c-8804-202c07bebe20
  region: asia-south1
  keyspace: main
  application.token: AstraCS:gZXNnccnbjZYvkNMebRFHbvq:0b0cf7f7d344c74e1687efec0d3b723c9db3a1aea9607bac163e2739c0ca4786